export const availableIcons = {
  Животные: ["IconBat", "IconCat", "IconDog"],
  Стрелки: [
    "IconArrowAutofitContent",
    "IconArrowBack",
    "IconArrowBadgeDown",
    "IconArrowBarUp",
    "IconArrowBigDown",
    "IconArrowElbowLeft",
    "IconArrowForward",
    "IconArrowLoopLeft",
    "IconArrowMerge",
    "IconArrowMoveDown",
    "IconArrowNarrowDown",
    "IconArrowRampLeft",
    "IconArrowRight",
    "IconArrowWaveLeftDown",
    "IconArrowsDiagonal",
    "IconArrowsDiff",
    "IconArrowsDown",
    "IconArrowsExchange",
    "IconArrowsHorizontal",
    "IconArrowsLeftRight",
    "IconArrowsMaximize",
    "IconArrowsMove",
    "IconArrowsRandom",
    "IconArrowsUp",
    "IconArrowsUpDown",
  ],
  "Искусство и дизайн": ["IconFeather", "IconPaint", "IconPalette"],
  "Награды и эмблемы": [
    "IconAward",
    "IconCertificate",
    "IconStar",
    "IconTrophy",
  ],
  "Бизнес и финансы": [
    "IconChartBar",
    "IconChartLine",
    "IconChartPie",
    "IconGraph",
  ],
  Коммуникация: [
    "IconMailbox",
    "IconMessage",
    "IconMicrophone",
    "IconNews",
    "IconPhone",
    "IconPin",
  ],
  "Коммерция и покупки": [
    "IconBox",
    "IconCoin",
    "IconGift",
    "IconShoppingCart",
    "IconWallet",
  ],
  "Документы и файлы": [
    "IconArchive",
    "IconBook",
    "IconBookmark",
    "IconBooks",
    "IconFile",
    "IconFileCheck",
    "IconFileDownload",
    "IconFilePlus",
    "IconFileText",
    "IconFolder",
    "IconStack",
  ],
  "География и путешествия": ["IconGlobe", "IconWorld"],
  "Природа и погода": [
    "IconCloud",
    "IconDroplet",
    "IconGrain",
    "IconLeaf",
    "IconMoon",
    "IconRecycle",
    "IconSnowflake",
    "IconSun",
    "IconTree",
    "IconUmbrella",
    "IconWind",
  ],
  "Безопасность и конфиденциальность": [
    "IconFingerprint",
    "IconId",
    "IconKey",
    "IconLock",
    "IconShield",
    "IconShieldCheckered",
  ],
  "Наука и математика": [
    "IconAbacus",
    "IconAtom",
    "IconBinaryTree",
    "IconFlask",
    "IconInfinity",
    "IconMagnet",
    "IconPlanet",
    "IconRocket",
    "IconTemperature",
  ],
  "Технологии и устройства": [
    "IconAccessPoint",
    "IconAntenna",
    "IconAppWindow",
    "IconApps",
    "IconBrowser",
    "IconBug",
    "IconCode",
    "IconCpu",
    "IconDatabase",
    "IconDevices",
    "IconMouse",
    "IconNetwork",
    "IconPlug",
    "IconPower",
    "IconPrinter",
    "IconRadar",
    "IconScan",
    "IconServer",
    "IconTerminal",
    "IconUsb",
    "IconWifi",
    "IconFaceId",
  ],
  "Время и дата": ["IconCalendar", "IconHourglass", "IconStopwatch"],
  "Инструменты и прочее": [
    "IconArmchair",
    "IconBinoculars",
    "IconHammer",
    "IconLamp",
    "IconLifebuoy",
    "IconPuzzle",
    "IconRuler",
    "IconScale",
    "IconScissors",
    "IconTool",
  ],
  "Интерфейс и действия": [
    "IconAdjustments",
    "IconAlarm",
    "IconAlertCircle",
    "IconAspectRatio",
    "IconBrightness",
    "IconCheck",
    "IconChecklist",
    "IconContrast",
    "IconCopy",
    "IconEdit",
    "IconEye",
    "IconFilter",
    "IconInfoCircle",
    "IconLink",
    "IconList",
    "IconNotification",
    "IconPaperclip",
    "IconDownload",
    "IconRefresh",
    "IconSearch",
    "IconSend",
    "IconShare",
    "IconSwitch",
    "IconThumbUp",
    "IconPointer",
    "IconZoom",
  ],
  "Пользователи и люди": ["IconUser", "IconUsers"],
  "Здания и дома": [
    "IconBuilding",
    "IconBuildingBurjAlArab",
    "IconBuildingCommunity",
    "IconBuildingFactory",
    "IconBuildingSkyscraper",
    "IconHome",
    "IconSmartHome",
  ],
  "Транспорт и навигация": [
    "IconAirBalloon",
    "IconCar",
    "IconCompass",
    "IconDirectionSign",
    "IconMap",
    "IconNavigation",
    "IconRoute",
    "IconTrain",
    "IconTruck",
  ],
  "3D и символы": [
    "Icon360",
    "Icon3dCubeSphere",
    "Icon3dRotate",
    "IconAnchor",
    "IconCircle",
    "IconSquare",
    "IconVector",
    "IconTarget",
  ],
};
