export enum OrganizationPermission {
    MANAGE_MEMBERS = 'ORGANIZATION_MANAGE_MEMBERS',
    MANAGE_ROLES = 'ORGANIZATION_MANAGE_ROLES',
    MANAGE_PROJECTS = 'ORGANIZATION_MANAGE_PROJECTS',
    MANAGE_SETTINGS = 'ORGANIZATION_MANAGE_SETTINGS'
}

export enum ProjectPermission {
    MANAGE_MEMBERS = 'PROJECT_MANAGE_MEMBERS',
    MANAGE_ROLES = 'PROJECT_MANAGE_ROLES',
    MANAGE_SETTINGS = 'PROJECT_MANAGE_SETTINGS',
    CREATE_TASKS = 'PROJECT_CREATE_TASKS',
    EDIT_TASKS = 'PROJECT_EDIT_TASKS',
    DELETE_TASKS = 'PROJECT_DELETE_TASKS',
    VIEW_TASKS = 'PROJECT_VIEW_TASKS',
    COMMENT_TASKS = 'PROJECT_COMMENT_TASKS',
    MANAGE_LABELS = 'PROJECT_MANAGE_LABELS'
}

export type Permission = OrganizationPermission | ProjectPermission; 